name: SSH CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest  # to use latest mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test # set the using database here "ilo-db" or "test"
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'node'  # to use latest  Node.js

    - name: Install dependencies (frontend)
      working-directory: ./frontend
      run: npm install

#    - name: Run frontend tests
#      working-directory: ./frontend
#      run: npm test

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build --if-present

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'  # to use latest  PHP
        extensions: mbstring, pdo, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./backend

    - name: Copy frontend build to backend
      run: cp -r ./frontend/dist/* ./backend/public

    - name: Generate application key
      run: php artisan key:generate
      working-directory: ./backend

    - name: Create .env file
      run: cp .env.example .env
      working-directory: ./backend

    - name: Update .env file
      run: |
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_DATABASE=homestead/DB_DATABASE=test/' .env   # need to set the mysql detail in practical use
        sed -i 's/DB_USERNAME=homestead/DB_USERNAME=root/' .env  
        sed -i 's/DB_PASSWORD=secret/DB_PASSWORD=root/' .env
      working-directory: ./backend

    - name: Run database migrations
      run: php artisan migrate
      working-directory: ./backend

#    - name: Run backend tests
#      run: php artisan test
#      working-directory: ./backend

    - name: Deploy to Serve
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" --exclude='.git' --exclude='node_modules' --exclude='vendor' ./backend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/deploy/backend/
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /path/to/deploy/backend && composer install && php artisan migrate --force && php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear"
